### PR TITLE
Improve load dialog

### PR DESCRIPTION
**Pull request by nthykier**
This PR improves the load dialog in two ways:

1. We add a text field so you can type in the save game name directly
2. If you type into the field, the dialog will hide games that does not match what you typed.

### CODE REVIEW

**Comment by Xenega** [comment]
Your pull request give me :
Fatal Python error: (pygame parachute) Segmentation Fault

**Comment by nthykier** [comment]
@Xenega Interesting.  Which version of pygame and python do you use?  I am on pygame 1.9.4.post1 and python 2.7.16+ with no issues.

**Comment by Xenega** [comment]
I have thought about it and I might better to not change the text field when we click on it. 

Conversely, we should automatically select the save when only one save is present in the list or when there a save with the same name the term we search.

What do you think about it ?

**Comment by nthykier** [comment]
If we do not change the text field when we click on an item in the listbox, then we need to change how we decide which save game is chosen.  At the moment, the text field decides the final name - the argument being that we will need that for the `save` menu because we cannot assume the item will be in the listbox (note that the final commit reuses this dialog for the `save` dailog).  I am open to suggestions for how we implement the logic, but I do not have a good suggestion of the bat.

I would be happy with selecting the relevant save game when there is an exact match. That should be trivial to do.

**Comment by Xenega** [comment]
Use the selected item.

**Comment by nthykier** [comment]
The `selected item` approach will not work for the save dialog as the name will not be in the list box (except for the case where you are replacing an existing save game)

**Comment by nthykier** [comment]
Changed the label text to "Filter", removed the code for loading the game based on the content of the text field (which is now solely a filter) and removed the commit that made the code use it as save dialog.

**Pull request merged**
