### PR TITLE
add new theme with russian font

### PR DESCRIPTION
**Pull request by DrMoriarty**
It's not easy to find free russian font with the same look&feel as the original one. So this solution isn't perfect but it allows to use russian localization.
Some screenshots:

### CODE REVIEW

**Comment by Xenega** [comment]
Adding a different theme is problematic. We should allows to fully localize theme (see #96).

**Comment by Xenega** [comment]
Use #98.

**Comment by DrMoriarty** [comment]
@Xenega I updated this PR to use variant theme

**Comment by Xenega** [comment]
I am sorry but the theme bug take more time to fix.

**Comment by Xenega** [comment]
Please rebase to testing/variant_theme. Otherwise I will do it.

**Comment by DrMoriarty** [comment]
@Xenega rebased

**Pull request merged**
