### PR TITLE
Added German translations for all buttons

### PR DESCRIPTION
**Pull request by Quix0r**
Please validate if button keys are not conflicting (didn't saw one here).

### CODE REVIEW

**Comment by Xenega** [comment]
Currently, hotkey test needs to be done manually.

**Comment by Quix0r** [comment]
So far I saw only buttons in Options page being translated, no where else. I think you currently transit to another system?

**Comment by Xenega** [comment]
Yes, everything will be in po.

**Comment by Xenega** [comment]
In another repository.

**Comment by Quix0r** [comment]
Oh, okay

**Comment by Xenega** [comment]
Hey, I could merged it before. :)

**Comment by Quix0r** [comment]
Ü

**Pull request merged**
