### PR TITLE
Display warning to players

### PR DESCRIPTION
**Pull request by Xenega**
Warning list:
* DONE => All cpu are not used
* DONE => Only one base left
* TODO => Not enough cash to build (#21)

Improvements:
* TODO => Display only one time a warning if player said continue except if situation change
* DONE => Display one dialog with multiple warning  
* TODO => Warning list screen

Don't hesitate to propose new warning.
This pull request can be merged partially. No commit depends of a later commit.

### CODE REVIEW

**Comment by Quix0r** [comment]
This may help indicating problems that might stop you from reaching game goal. I would like to see this being included in main repos.

**Comment by Quix0r** [comment]
This PR has conflicts.

**Comment by rofl0r** [comment]
ouch, i would strongly suggest **not** to use a merge-master-into-branch approach; this creates a very ugly git history. IMO it is preferable to export the commits of this branch as patches (git format-patch) and then apply them on top of master (if automatic application with `git am` fails, one can do the changes of the patch manually).

**Comment by Xenega** [comment]
@rofl0r I know. Let's me work. :P

**Pull request merged**
