### PR TITLE
Reduce file descriptor usage due to fonts

### PR DESCRIPTION
**Pull request by nthykier**
Mitigates #156 by only loading the font sizes we need as we need them.
With this, we go from loading 200 instances of Font to less than 70
at the start of the game.

Signed-off-by: Niels Thykier <niels@thykier.net>

### CODE REVIEW

**Comment by sunfall** [comment]
Can you make the lazy font cache an actual LRU cache rather than rejecting requests after the first hundred?  You can store the tick at which each font gets requested, and then when the 101th is asked for, delete the, say, 20 oldest.  I'm worried that a full-game playthrough may in fact use more than 100 fonts and crash.

**Comment by nthykier** [comment]
The font cache class is "local" and only covers different sizes of a given font, so the LRU would be on the given sizes of the same front (and not across all fonts).  Secondly, I have not actually changed the worst case AFAICT - the only code would eagerly load 100 instances of each font mentioned in the theme.  Now we just do it lazily?

**Comment by Xenega** [comment]
The game will only crash if we use a font with a size superior to 100 point. 

Anyone to test Singularity in 4K ? :)

**Comment by nthykier** [comment]
If we are going to do a LRU thing, we should also ensure that nothing else is caching/referencing the font.  Otherwise, we may just end up with multiple copies of the font (+size) because something keeps the "evicted" version alive.

**Comment by sunfall** [comment]
Oh, derp, I missed that it was per font and not global, so this is a strict improvement.  My bad!  Ignore me, then.

**Pull request merged**
