### PR TITLE
Variant Theme

### PR DESCRIPTION
**Pull request by Xenega**
Implement #96.

I still needs to fix the restart bug for theme.

Please test it.

### CODE REVIEW

**Comment by DrMoriarty** [comment]
How should I create new theme in order to use this feature?

**Comment by DrMoriarty** [comment]
I copied new font to `data/themes/default/fonts/superstar_memesbruh03.ttf` and have made `data/themes/default/theme_ru_RU.dat` with this content:
```
[fonts]
special = superstar_memesbruh03.ttf
```
Than I selected russian locale and selected the default theme. Also I restarted game (several times). 

As you can see there are no custom font.

**Comment by DrMoriarty** [comment]
It was my fault. I mistyped in file name. It works pretty well:

I will update my PR soon.

**Comment by Xenega** [comment]
Cool. I just need to fix the bug.

**Comment by Xenega** [comment]
@DrMoriarty I fixed the problem with theme restart. Could you test it ?

**Comment by Xenega** [comment]
Corrected some bugs. Think it good now. Will be push it tomorow.

**Pull request closed without merging**
