### PR TITLE
Testing balancing of the game

### PR DESCRIPTION
**Pull request by Xenega**
Main issue [here](https://github.com/singularity/singularity/issues/75).

### CODE REVIEW

**Comment by PeterJust** [comment]
It says:
`# python singularity.py -s`
`Invalid string section jobs.`

**Comment by Xenega** [comment]
Found the error. It's with translation.

**Comment by Xenega** [comment]
Should be solved with b35a98d.

**Comment by nthykier** [comment]
The Storage Unit is an excellent addition; it does very well to cover that middle area between rented/stolen PC and the small warehouse.  It also enables you to research medium techs without having to by a small warehouse as well and made the game much more enjoyable to me.  Even with  the nerfing of the Quantum MK II and MK III, the end game did not pose any particular issues.

I would recommend merging this as it is and then look at some other areas of rebalancing afterwards:

 * As @PeterJust already mentioned, the storage unit can die before you can get CPUs into it (I tried with the `server`).
 * The jump from `cluster` PC to the next level feels to expensive.  It is a factor 10 in price but only a factor 4 in compute power.  It makes me stay with cluster until I reach quantum computers.
    * Maybe *also* make the CPU time for higher level CPU types more expensive, so that quantum computers are less trivial to research with two warehouses with cluster computers.
 * I get Lunar bases about at the same time as undersea labs.  As Lunar bases have about 75 times as much space for compute, undersea labs are mostly redundant - particularly, it can never pay off to buy a large undersea lab for me.
    * This might be solved by balancing the CPU types between cluster and quantum computers, as reaching quantum computers are effective enough to get almost every tech there is on Earth.
 * Lunar bases may still be a bit too over powered (or too easy to obtain).  They are an order of magnitude stronger CPU-wise than any other base on Earth and it is almost impossible to detect.

@Xenega: Thanks for working on improving singularity. :)

**Comment by nthykier** [comment]
Forgot to mention:  While I love the Storage Unit from a balance PoV, I am not sure it makes sense to allow the storage unit to have a generator or warning signs/fences on the storage unit (it worked fine from a balance PoV, but ...).  I am not even sure that a storage unit have sufficient power and cooling systems to handle the servers.

**Comment by Xenega** [comment]
1. It's random. Some base die fast, other can beat record of longevity. Base has already a grace period when built to avoid too early detection.  

2. The gap exists but finally I don't think it's intentional and we can forget it. Why keep it when we know it's not good ?
_Cluster_ => 5000
_Mainframe_ => 15000
_Supercomputer_ => 40000

3-4. _Undersea Lab_ take too many time to build, making it useless.
_Cover Base_ => 12
_Undersea lab_  => 8
_Large Undersea Lab_ => 16
Otherwise _Lunar Base_ is too large.
I think we can add few base :
_Lunar Module_ => 14 
_Small Lunar Facility_ => 70 (needs _Spacefaring Installation_)
_Large Lunar Facility_ => 210 (needs _Advanced Spacefaring Installation_)
_Small Scientific Outpost_ => 25
_Large Scientific Outpost_ => 125 (needs _Advanced Spacefaring Installation_)
Otherwise, Lunar Rocketry should need to be done in danger 1 location. You cannot have fun with rocket near human habitation. Danger 1 should be "far from human activities" and antarctic should be danger 1.

5. Hey, a lot of person started with server in a garage. So I think singularity can handle it. There exist small generator, so it's not a problem in small place. Warning Signs and Perimeter Fencing is another things, but is it really that problematic ?

**Comment by Xenega** [comment]
And I think we can make more advanced base needed for quantum computer.
_Project: Synchrotron_, danger 1, prerequisite for quantum computer.

**Comment by nthykier** [comment]
1/ The grace of the storage unit seems rather short compared to other bases then.  I rarely experience a warehouse being found before the CPUs have been delivered and it has run for a day or two.  But with the Storage Unit, I lost it 3-4 times almost immediately after getting the CPU delivered.

2/ Those price changes seems to work.  At least now the price per CPU improves with each upgrade from cluster to super computer.  I am happy with it. :)

3/ - 4/ It seems like a good step - this time the undersea lab seems to be useful as the alternative (covert base) is simply too small.  Admittedly, an undersea lab with Quantum MK III can still research `Spacefaring Installation` and `Advanced Spacefaring Installation` within a few days.  They should probably be more expensive or have a higher danger level.

5/ Game-wise, it is not a problem.  However it pokes at my `suspension of disbelief` and the items do not match the bases.  Among other, I can also install a Solar Collector in the Storage Unit as a means to avoid suspicion.  But installing a Solar Collector in a "walled off storage unit without windows" should give any bonus and would probably be the talk of the day at the Storage Unit firm ("I heard someone installed a solar collector inside Unit 325")

6/ Seems fine with the `Project: Synchrotron`- was it intentional that only the Project had a danger level and the Quantum computing afterwards were still researchable every where?

**Comment by nthykier** [comment]
... and now for some bugs, that I experienced while play-testing the branch.

After reaching the Moon and researching `Spacefaring Installation` and `Advanced Spacefaring Installation`, I hit the following exception and the moon base menu now gives the main menu.

```
Exception in function show at Wed Jul 25 11:12:26 2018 CEST:
Traceback (most recent call last):
  File ".../singularity/code/safety.py", line 47, in safe_call
    return func(*args, **kwargs)
  File ".../singularity/code/graphics/dialog.py", line 202, in show
    result = self.handle(event)
  File ".../singularity/code/graphics/dialog.py", line 329, in handle
    return self.call_handlers(handlers, event)
  File ".../singularity/code/graphics/dialog.py", line 341, in call_handlers
    handler(event)
  File ".../singularity/code/graphics/button.py", line 154, in handle_event
    self.activate_with_sound(event)
  File ".../singularity/code/graphics/button.py", line 167, in activate_with_sound
    self.activated(event)
  File ".../singularity/code/graphics/button.py", line 195, in activated
    self.function(*self.args, **self.kwargs)
  File ".../singularity/code/screens/map.py", line 410, in open_location
    dialog.call_dialog(self.location_dialog, self)
  File ".../singularity/code/graphics/dialog.py", line 96, in call_dialog
    retval = dialog.show()
  File ".../singularity/code/screens/location.py", line 138, in show
    return super(LocationScreen, self).show()
  File ".../singularity/code/graphics/dialog.py", line 188, in show
    Dialog.top.maybe_update()
  File ".../singularity/code/graphics/widget.py", line 323, in maybe_update
    self.update()
  File ".../singularity/code/graphics/widget.py", line 327, in update
    self.prepare_for_redraw()
  File ".../singularity/code/graphics/widget.py", line 319, in prepare_for_redraw
    child.prepare_for_redraw()
  File ".../singularity/code/graphics/widget.py", line 319, in prepare_for_redraw
    child.prepare_for_redraw()
  File ".../singularity/code/graphics/widget.py", line 319, in prepare_for_redraw
    child.prepare_for_redraw()
  File ".../singularity/code/graphics/widget.py", line 306, in prepare_for_redraw
    self.rebuild()
  File ".../singularity/code/graphics/dialog.py", line 649, in rebuild
    self.desc_func(self.description_pane, key)
  File ".../singularity/code/screens/location.py", line 248, in on_change
    name = generate_base_name(self.parent.location, base_type)
  File ".../singularity/code/screens/location.py", line 292, in generate_base_name
    flavor = random.choice(base_type.flavor)
  File "/usr/lib/python2.7/random.py", line 277, in choice 
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
```

**Comment by nthykier** [comment]
For startup, I got the following crash:

```
$ ./singularity
Traceback (most recent call last):
  File "./singularity", line 23, in <module>
    import code.singularity
  File ".../singularity/code/singularity.py", line 284, in <module>
    g.load_bases()
  File ".../singularity/code/g.py", line 574, in load_bases
    load_base_defs()
  File ".../singularity/code/g.py", line 517, in load_base_defs
    load_generic_defs("bases",base_type,lang,["flavor"])
  File ".../singularity/code/g.py", line 501, in load_generic_defs
    if key in dir(object[item["id"]]):
KeyError: 'Lunar Facility'
```

The following change seems to fix it:


```diff
$ git diff
diff --git a/data/bases_str.dat b/data/bases_str.dat
index 9f50088..60ca322 100644
--- a/data/bases_str.dat
+++ b/data/bases_str.dat
@@ -50,10 +50,10 @@ name = Time Capsule
 description = (1 CPU) This base consists of nothing more than a small
computer and a satellite link. It is nearly undetectable.
 flavor_list = Time Capsule | Capsule

-[Lunar Facility]
-name = Lunar Facility
+[Lunar Module]
+name = Lunar Module
 description = This base is a series of caverns dug into the Moon's
surface. Due to the lack of neighbors, this base is quite large.
-flavor_list = Dome | Lunar Facility | Lunar Base
+flavor_list = Dome | Lunar Module | Lunar Base

 [Scientific Outpost]
 name = Scientific Outpost
```

**Comment by nthykier** [comment]
I have made a branch for adding English texts to this branch (see https://github.com/nthykier/singularity/tree/testing-balancing-english).  It includes the bases_str.dat change mentioned above.

**Comment by nthykier** [comment]
Bug: `Large Scientific Outpost` is not buildable.  I suspect that `pre` does not accept ` | ` like other fields (if I remove the ` | Advanced Spacefaring Installation` in the data file, then the base becomes buildable)

**Comment by nthykier** [comment]
The `Reality Bubble` should either become cheaper now (with the Lunar base nerfed) or we need another way to get a larger income.  Otherwise, then end game just becomes grinding of money on the Moon/Far Reaches.

**Comment by Xenega** [comment]
I solved the bug. Needs some time to test it more.

**Comment by PeterJust** [comment]
Here is a first draft of my balancing effort:
[balancing.py.zip](https://github.com/singularity/singularity/files/2358429/balancing.py.zip)
The file is to be executed in the singularity root directory, preferably from within an IDE.
What it does (up till now):
It takes a targeted profit (defined as a multiple of the investment cost), and returns the necessary discovery rate, to let the base die (in the mean) at the appropriate time.

I got influenza this week, so I wasn't able to finish it.

**Comment by Xenega** [comment]
Since I hate the old ending, I take the opportunity to modify the ending. Need writer.

**Comment by Xenega** [comment]
I will push validated change and I will recreate this branch later.

**Pull request closed without merging**
