### PR TITLE
Add option to disable unused CPU warnings

### PR DESCRIPTION
**Pull request by cryptarch**
I am a heavy user of CPU Pool task, which allocates unused CPUs to working jobs for money. I find that the frequent warnings about unused CPUs when they are actually being used for jobs really breaks the flow of the game.

The changes in this pull request add an option to disable those warnings.

I modelled the new option after `daynight`, so in particular it adds a new global setting in `code/g.py`.

It wasn't obvious what the best place would be to add the new option in the Options screen. I decided it would be best to create a new row under the existing options for two reasons:

1. There seems to be enough room there
2. Looking in the code, there are warnings when you are in danger of losing your last base. A sixth option row provides a place where the base warnings could be toggled as well, if that is implemented in future.

### CODE REVIEW

**Comment by Xenega** [comment]
Thanks. It's a common request (see #83). I tried to make it before, but was disappointed by my implementation.

Basically, all warnings must be able to be disabled. So, a implementation about a particular case is not good. It would be only temporary, and I'm reticent to add temporary code to the codebase that contains already too many. You don't need to completely make everything, just take it into consideration.

So daylight is not good example. 

1/ It's better than you create a third tabs to put the new option. We may call this tabs 'GUI' to centralise GUI options.

2/ Make the new tabs so we can easily add new options for other warnings.

3/ You must use a dictionary to save disabled warning. 

4/ I am somewhat divided if this options must be global or game dependent. 

We could use some dispatch to handle the warning code in the future.

**Comment by cryptarch** [comment]
Hi Xenega,

Thanks for clarifying the position on this. I tried looking for existing issues but I didn't notice #83.

In the #83 discussion you said the warning is only intended to happen one time. If I found a way to make it only happen one time, instead of all the time, would it be likely such a pull request would be approved?

> It's better than you create a third tabs to put the new option. We may call this tabs 'GUI' to centralise GUI options.

Creating a new tab for GUI options would be a good idea. There are a few other GUI changes I would like to make as well.

For example, I tried creating a custom theme (a black-and-red "night mode" theme), but I found some GUI colours are hard-coded instead of following the theme. This had the result that my custom theme did not look good. I would like to add an option to change the hard-coded GUI elements as well. So, a GUI options tab would help me in two ways :)

> You must use a dictionary to save disabled warning

I might need guidance on how to do this properly. I am not a strong Python programmer.

> I am somewhat divided if this options must be global or game dependent

I didn't realise it is possible to create game-dependent options. Does that exist already or would game-dependent options need to be implemented from scratch?

If game-dependent options are not implemented yet, then maybe that should be a first step before doing the GUI options tab. There are other options that could be game-dependent, such as `daynight`, preferred language, and theme.

Happy to hear your thoughts about how to progress things from here. I really want to fix the cpu warnings, they are so annoying! :D

**Comment by Xenega** [comment]
Hi,

About one time warning, what I thought is, if nothing changed, we should not asked again. It's a little complicated to do, but, yes, if you could do it, the pull request would be approved.

Anyways, we needs a preference for people who never want a warning.

> I didn't realise it is possible to create game-dependent options. Does that exist already or would game-dependent options need to be implemented from scratch?

Currently, no. We could put it in player, a lot of things are saved for player are here, but a structure would be better. Let forget it now, I could bring it later.

> I might need guidance on how to do this properly. I am not a strong Python programmer.

#g.py
```python
warnings = {
            "warning_cpu_usage": None,
}
```
#singularity.py
```python
g.warnings["warning_cpu_usage"] = prefs.getboolean("Warning", "warning_cpu_usage")
```

#warnings.py
```python
def check_warning(warning_id)
    return g.warnings[warning_id] == None or g.warnings[warning_id]

if (check_warning("warning_cpu_usage")):
   pass 
```

Where you can, use a loop to prepare future addition.

For example:
#singularity.py
```python
for warning_id in g.warnings:
    try:
        g.warnings[warning_id] = prefs.getboolean("Warning", warning_id)
    except:
        pass # don't be picky
```

> For example, I tried creating a custom theme (a black-and-red "night mode" theme), but I found some GUI colours are hard-coded instead of following the theme. This had the result that my custom theme did not look good. I would like to add an option to change the hard-coded GUI elements as well. So, a GUI options tab would help me in two ways :)

Hardcoded things is just a long combat I have with this codebase. Tell me where and I shoot. The issue are here #57 and here #71.

**Comment by cryptarch** [comment]
Hi @Xenega 

Thanks for that. Since it sounds like you are in favour of attacking hard-coded colours, I'll raise a separate issue for dealing with that :)

I'll also have a look at the code to see if I can figure out how to make the warning only appear one time.

**Comment by Xenega** [comment]
@cryptarch Do you intend to continue your pr? Do you need more help?

**Comment by cryptarch** [comment]
Hi @Xenega It would be good to keep progressing this. I can try looking into it this weekend.

**Comment by cryptarch** [comment]
Hi @Xenega 

I think I deleted the fork for dealing with this pull request. I needed to start from scratch anyway since my implementation was too specific. So, I think the current PR should be closed.

**Pull request closed without merging**
